SELECT
HISTORY_ID,
CAR_ID,
DATE_FORMAT(START_DATE, '%Y-%m-%d') as START_DATE,
DATE_FORMAT(END_DATE, '%Y-%m-%d') as END_DATE,
if(DATEDIFF(END_DATE, START_DATE) >= 29, '장기 대여', '단기 대여') as RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') like '2022-09'
order by HISTORY_ID desc
-- DATEDIFF(END_DATE, START_DATE) >= 29인 이유는 당일도 포함이기 때문에
-- 원래 조건인 30일에서 -1 해서 29로 조건 적용